"""empty message

Revision ID: 0306b7849892
Revises: bd636b797147
Create Date: 2022-03-15 11:26:19.670383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0306b7849892'
down_revision = 'bd636b797147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_file', sa.LargeBinary(), nullable=True),
    sa.Column('picture_file', sa.LargeBinary(), nullable=True),
    sa.Column('analytics', sa.Integer(), nullable=True),
    sa.Column('cardio_file', sa.Float(precision=4), nullable=True),
    sa.Column('quest_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('datatable',
    sa.Column('id_table', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('users_data_id', sa.Integer(), nullable=True),
    sa.Column('date_time_added', sa.DateTime(), nullable=True),
    sa.Column('expname', sa.String(length=20), nullable=True),
    sa.Column('tools', sa.String(length=40), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_data_id'], ['user_data.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['userlogs.id'], ),
    sa.PrimaryKeyConstraint('id_table')
    )
    op.create_table('fitbit_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userlogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fitbit_tokens')
    op.drop_table('datatable')
    op.drop_table('userlogs')
    op.drop_table('user_data')
    # ### end Alembic commands ###
