"""Association object fix

Revision ID: 0bbb48519a2e
Revises: 0ee09a895d53
Create Date: 2022-03-01 10:49:16.680872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bbb48519a2e'
down_revision = '0ee09a895d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_constraint('datatable_ibfk_2', 'datatable', type_='foreignkey')
    op.create_foreign_key(None, 'datatable', 'userlog', ['users_id'], ['id'])
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datatable', type_='foreignkey')
    op.create_foreign_key('datatable_ibfk_2', 'datatable', 'users', ['users_id'], ['id'])
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.drop_table('userlog')
    # ### end Alembic commands ###
