"""fixing relationship in user

Revision ID: 136b4f3322c0
Revises: 4f73262f8f5f
Create Date: 2022-03-30 16:08:56.332898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136b4f3322c0'
down_revision = '4f73262f8f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_data_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_datatable_users_data_id_user_data'), 'user_data', ['users_data_id'], ['id'])

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_data_users_table_id_datatable', type_='foreignkey')
        batch_op.drop_column('users_table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_table_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_data_users_table_id_datatable', 'datatable', ['users_table_id'], ['id_table'])

    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_datatable_users_data_id_user_data'), type_='foreignkey')
        batch_op.drop_column('users_data_id')

    # ### end Alembic commands ###
