"""empty message

Revision ID: 26d9f8753ef8
Revises: bd636b797147
Create Date: 2022-04-20 14:51:01.471040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26d9f8753ef8'
down_revision = 'bd636b797147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.drop_constraint('datatable_ibfk_1', type_='foreignkey')
        batch_op.drop_column('users_data_id')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_table_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timer', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('check', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_data_users_table_id_datatable'), 'datatable', ['users_table_id'], ['id_table'])

    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(batch_op.f('uq_userlogs_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_userlogs_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_userlogs_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_userlogs_email'), type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_data_users_table_id_datatable'), type_='foreignkey')
        batch_op.drop_column('check')
        batch_op.drop_column('timer')
        batch_op.drop_column('users_table_id')

    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_data_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('datatable_ibfk_1', 'user_data', ['users_data_id'], ['id'])

    # ### end Alembic commands ###
