"""gamedata added

Revision ID: 2d525c1c7a1c
Revises: 26d9f8753ef8
Create Date: 2022-05-03 13:32:06.052851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d525c1c7a1c'
down_revision = '26d9f8753ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leftclk', sa.Integer(), nullable=True),
    sa.Column('rightclk', sa.Integer(), nullable=True),
    sa.Column('upclk', sa.Integer(), nullable=True),
    sa.Column('spaceclk', sa.Integer(), nullable=True),
    sa.Column('game_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_data_id'], ['user_data.id'], name=op.f('fk_gamedata_game_data_id_user_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gamedata'))
    )
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('analytics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analytics', sa.INTEGER(), nullable=True))

    op.drop_table('gamedata')
    # ### end Alembic commands ###
