"""fixing relationship in user

Revision ID: 36a5c159f2ab
Revises: 50f5de5cf8dc
Create Date: 2022-03-30 16:31:49.642655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a5c159f2ab'
down_revision = '50f5de5cf8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_data_users_table_id_user_data', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_data_users_table_id_datatable'), 'datatable', ['users_table_id'], ['id_table'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_data_users_table_id_datatable'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_data_users_table_id_user_data', 'user_data', ['users_table_id'], ['id'])

    # ### end Alembic commands ###
