"""added uselist=False to backref

Revision ID: 4f73262f8f5f
Revises: 4fc232e0acb9
Create Date: 2022-03-30 14:55:03.489799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f73262f8f5f'
down_revision = '4fc232e0acb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_userlogs_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_userlogs_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_userlogs_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_userlogs_email'), type_='unique')

    # ### end Alembic commands ###
