"""initial migration

Revision ID: 4fc232e0acb9
Revises: e3c966d586de
Create Date: 2022-03-29 18:15:32.903477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc232e0acb9'
down_revision = 'e3c966d586de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatable', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users_data_id')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'datatable', ['users_table_id'], ['id_table'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('users_table_id')

    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_data_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user_data', ['users_data_id'], ['id'])

    # ### end Alembic commands ###
