"""added quest column to table

Revision ID: 90bf17a7f0bd
Revises: 2d525c1c7a1c
Create Date: 2022-05-05 20:12:12.624504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bf17a7f0bd'
down_revision = '2d525c1c7a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quests', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatable', schema=None) as batch_op:
        batch_op.drop_column('quests')

    # ### end Alembic commands ###
