"""Add check in UserData

Revision ID: 92abe9c48d5c
Revises: 0306b7849892
Create Date: 2022-03-17 15:08:18.092898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92abe9c48d5c'
down_revision = '0306b7849892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'check')
    # ### end Alembic commands ###
