"""Fix m2m migration

Revision ID: 9dd6bfe67506
Revises: ffb53c55b72e
Create Date: 2022-02-28 12:03:16.814063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dd6bfe67506'
down_revision = 'ffb53c55b72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('UserData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_file', sa.LargeBinary(), nullable=True),
    sa.Column('picture_file', sa.LargeBinary(), nullable=True),
    sa.Column('analytics', sa.Integer(), nullable=True),
    sa.Column('cardio_file', sa.Float(precision=4), nullable=True),
    sa.Column('quest_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserTable',
    sa.Column('id_table', sa.Integer(), nullable=False),
    sa.Column('date_time_added', sa.DateTime(), nullable=True),
    sa.Column('expname', sa.String(length=20), nullable=True),
    sa.Column('tools', sa.String(length=40), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['UserData.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id_table')
    )
    op.drop_table('user_table')
    op.drop_table('user_data')
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('user_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_file', sa.BLOB(), nullable=True),
    sa.Column('picture_file', sa.BLOB(), nullable=True),
    sa.Column('analytics', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cardio_file', mysql.FLOAT(), nullable=True),
    sa.Column('quest_file', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_table',
    sa.Column('id_table', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time_added', mysql.DATETIME(), nullable=True),
    sa.Column('expname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tools', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_table'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserTable')
    op.drop_table('UserData')
    op.drop_table('User')
    # ### end Alembic commands ###
