"""Initial migration

Revision ID: c11a6ae82d4a
Revises: 
Create Date: 2022-02-16 17:30:10.970981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c11a6ae82d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_data', 'user', ['user_id'], ['id'])
    op.drop_column('user_data', 'parttaker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('parttaker_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.drop_column('user_data', 'user_id')
    op.drop_column('user_data', 'id')
    # ### end Alembic commands ###
