"""added analty_file to UserData

Revision ID: cf95eea9171b
Revises: 90bf17a7f0bd
Create Date: 2022-05-09 19:21:01.850392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf95eea9171b'
down_revision = '90bf17a7f0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyt_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('analyt_file')

    # ### end Alembic commands ###
