"""empty message

Revision ID: ffb53c55b72e
Revises: c11a6ae82d4a
Create Date: 2022-02-28 11:49:11.629612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb53c55b72e'
down_revision = 'c11a6ae82d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_file', sa.LargeBinary(), nullable=True),
    sa.Column('picture_file', sa.LargeBinary(), nullable=True),
    sa.Column('analytics', sa.Integer(), nullable=True),
    sa.Column('cardio_file', sa.Float(precision=4), nullable=True),
    sa.Column('quest_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id_table', sa.Integer(), nullable=False),
    sa.Column('date_time_added', sa.DateTime(), nullable=True),
    sa.Column('expname', sa.String(length=20), nullable=True),
    sa.Column('tools', sa.String(length=40), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_table')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('user_data')
    op.drop_table('user')
    # ### end Alembic commands ###
